/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
/* Header for class soundJNI */

#ifndef _Included_soundJNI
#define _Included_soundJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef soundJNI_time
#define soundJNI_time 200L
/*
 * Class:     soundJNI
 * Method:    init_manager
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_soundJNI_init_1manager
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     soundJNI
 * Method:    new_link
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_soundJNI_new_1link
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     soundJNI
 * Method:    destory_link
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_soundJNI_destory_1link
  (JNIEnv *, jclass, jint);

/*
 * Class:     soundJNI
 * Method:    destory_manager
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_soundJNI_destory_1manager
  (JNIEnv *, jclass);

/*
 * Class:     soundJNI
 * Method:    get_cache_size
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_soundJNI_get_1cache_1size
  (JNIEnv *, jclass, jint);

/*
 * Class:     soundJNI
 * Method:    write_link
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_soundJNI_write_1link
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     soundJNI
 * Method:    write_link_wait_cache
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_soundJNI_write_1link_1wait_1cache
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     soundJNI
 * Method:    get_cache_alive
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_soundJNI_get_1cache_1alive
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
